Repository UWmathNEWS/slugline-web, pull requests merged in 2020-05, with the labels that each got.

#6 Add support for article editing flow
  src/App.tsx
  src/admin/Admin.tsx
  src/api/api.ts
  src/api/hooks.ts
  src/auth/AuthProvider.tsx
  src/dash/Dash.tsx
  src/dash/DashArticlesPage.scss
  src/dash/DashArticlesPage.tsx
  src/dash/EditorPage.tsx
  src/editor/EditorControls.scss
  src/editor/EditorInfo.scss
  src/editor/EditorInfo.tsx
  src/editor/SluglineEditor.scss
  src/editor/SluglineEditor.tsx
  src/issues/IssuePage.tsx
  src/issues/IssuesList.tsx
  src/profile/ProfileForm.tsx
  src/shared/hooks.ts
  src/shared/icons.ts
  src/shared/types.ts
Labels: Needs Squash

#9 Add basic CI
  .github/workflows/master.yml
  README.md
Labels: Needs Squash, enhancement

#16 Add useful test
  .github/workflows/master.yml
  src/App.test.tsx
Labels: devops

#19 Absolutely critical bug fix
  README.md
Labels: P3, documentation

#18 Allegedly fix hundreds of security vulnerabilities
  .github/workflows/master.yml
  package-lock.json
  package.json
Labels: Needs Squash, devops

#22 Cache dependencies when testing
  .github/workflows/master.yml
Labels: devops

#13 Migrate the ProfileForm to react-hook-form
  src/admin/UserList.tsx
  src/dash/EditorPage.tsx
  src/dash/articles/DashArticlesPage.tsx
  src/dash/issues/DashIssueDetail.tsx
  src/dash/issues/DashIssuesPage.tsx
  src/profile/Profile.tsx
  src/profile/ProfileForm.tsx
  src/shared/errors.ts
  src/shared/form/Field.tsx
  src/shared/form/util.ts
  src/shared/hooks.ts
  src/shared/types.ts
Labels: Blocking

#24 Run npm ci instead of npm install for ci
  .github/workflows/master.yml
Labels: devops

#20 Introduce tests (part 1)
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/__mocks__/axios.ts
  src/__tests__/App.int.test.tsx
  src/api/__tests__/api.unit.test.ts
  src/api/__tests__/hooks.unit.test.ts.tsx
  src/api/api.ts
  src/api/hooks.ts
  src/auth/AuthProvider.tsx
  src/auth/PrivateRoute.tsx
  src/auth/__tests__/PrivateRoute.unit.test.tsx
  src/header/SluglineNav.tsx
  src/index.tsx
  src/setupTests.ts
  src/shared/errors.ts
  src/shared/test-utils.ts
Labels: devops

#17 Font fixes
  src/_slugline_fonts.scss
  src/_slugline_vars.scss
  src/slugline.scss
Labels: bug, enhancement

#29 Introduce tests (part 2)
  package-lock.json
  src/profile/ProfileForm.tsx
  src/shared/__tests__/errors.unit.test.ts
  src/shared/__tests__/hooks.unit.test.ts
  src/shared/errors.ts
  src/shared/errors/__tests__/ErrorPage.unit.test.tsx
  src/shared/form/Field.tsx
  src/shared/form/NonFieldErrors.tsx
  src/shared/form/__tests__/Field.unit.test.tsx
  src/shared/form/__tests__/NonFieldErrors.unit.test.tsx
  src/shared/form/__tests__/util.unit.test.ts
Labels: Blocking

#26 Optimize CI
  .github/workflows/build.yml
  .github/workflows/master.yml
  .github/workflows/security.yml
Labels: devops

#28 Add check for type errors as part of CI
  .github/workflows/build.yml
Labels: devops

#31 Badges
  .github/workflows/security.yml
  README.md
Labels: devops

#25 Fix issues in RichTable
  .prettierrc
  package-lock.json
  package.json
  src/admin/UserList.tsx
  src/api/__tests__/hooks.unit.test.ts.tsx
  src/api/hooks.ts
  src/shared/components/Loader.scss
  src/shared/components/Loader.tsx
  src/shared/components/RichTable.scss
  src/shared/components/RichTable.tsx
  src/slugline.scss
Labels: Blocking

#34 Modernize AuthProvider
  src/App.tsx
  src/__tests__/App.int.test.tsx
  src/admin/UserList.tsx
  src/api/__tests__/hooks.unit.test.ts.tsx
  src/api/hooks.ts
  src/auth/Auth.ts
  src/auth/AuthProvider.tsx
  src/auth/Login.tsx
  src/auth/PrivateRoute.tsx
  src/auth/__tests__/Auth.unit.test.ts
  src/auth/__tests__/AuthProvider.unit.test.tsx
  src/auth/__tests__/PrivateRoute.unit.test.tsx
  src/header/SluglineNav.tsx
  src/profile/Profile.tsx
  src/profile/ProfileForm.tsx
  src/shared/test-utils.ts
  src/shared/types.ts
Labels: Blocking
