Repository UWmathNEWS/slugline-web, pull requests merged in 2020-06, with the labels that each got.

#36 Size limit test
  .github/workflows/build.yml
  .github/workflows/size-limit.yml
  .size-limit.json
  package-lock.json
  package.json
Labels: devops

#46 Caching for size-limit
  .github/workflows/size-limit.yml
  .size-limit.json
  package.json
Labels: devops

#52 Only track file sizes with size-limit
  .size-limit.json
  package-lock.json
  package.json
Labels: bug, devops

#63 Update size-limit-action to 1.4.0
  .github/workflows/build.yml
Labels: devops

#65 Fix race condition in PrivateRoute
  package-lock.json
  package.json
  src/__tests__/App.int.test.tsx
  src/api/__tests__/api.unit.test.ts
  src/api/api.ts
  src/auth/PrivateRoute.tsx
  src/auth/__tests__/PrivateRoute.unit.test.tsx
Labels: P1, enhancement, tests

#59 Add tests for RichTable
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/setupTests.ts
  src/shared/__tests__/hooks.unit.test.ts
  src/shared/components/RichTable.tsx
  src/shared/components/__tests__/Loader.unit.test.tsx
  src/shared/components/__tests__/RichTable.unit.test.tsx
  src/shared/components/__tests__/Visor.unit.test.tsx
  src/shared/hooks.ts
  src/shared/test-utils.tsx
Labels: tests
